version: '3.8'
services:
  postgres:
    container_name: "badges_db"
    image: 'postgres:latest'
    restart: always
    user: postgres
    volumes:
      - postgres_volume:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=pass1234
      - POSTGRES_DB=badges
    ports:
      - '5450:5432'
  
  redis:
    container_name: "badges_redis"
    image: 'redis:7-alpine'
    restart: always
    command: redis-server --appendonly yes
    volumes:
      - redis_volume:/data
    ports:
      - '6379:6379'
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3

volumes:
  postgres_volume:
  redis_volume:
