name: build

on:
  push:

jobs:
  build:
    uses: decentraland/platform-actions/.github/workflows/apps-with-db-build.yml@0149168ee31ef65e3095e2175a4a23087e49fc0c # TODO: update this to main when the repo is public and configured on Coveralls
